language: ruby
sudo: false
rvm:
  - 2.6
env:
  global:
    # AWS_ACCESS_KEY_ID for S3 deployment
    - secure: "BIFbtHSRX3STLFDTcBMKJ38/00FKLFmavyAdTY4KkqQYaGqjpWChPOIVA7iKv1WdSZjn0gLM6HfGBgvUF3pSEstdxGnOTbLtY/9QXYpoCIh5tLAsRsq9vPo1yv0y1TDpLX0NSPgry8EDApUIROf8bUmSTqfsbsoWnkstq+Ckg30="
    # AWS_SECRET_ACCESS_KEY for S3 deployment
    - secure: "Zs84AWMeVxKhr09o6XpJdGJ2XQGD7eQobQp5YQgnz2u46mwBsEDnOUQB7RADBj2zss4/mi4rVxaiSZdgPUmn5A8X1Oets9cL0/H7SvSICT1ADIkxeLzAZoRDEM20zHMbisWRN8i1l1ULeAoqLp9kRp57Ob6oB9b7K4+a/Kq9s5k="
    # INDIGO_API_AUTH_TOKEN
    - secure: "fljdfxbOeNSeJzg8mesDsLbutUwjiJbbz4wp9rqoWtzA63eFNTC2OuHrhGcO8Whh/a1mkPnyMqWdgg1eejk+g7JBmNbxr7AQOcx5CkNxDTYKvGKLoNcfOdoW4fk3tQ/hIjinNE8evRX00PIlFdrIe/JnZM3YV4flNzKvjeT3l9k="
script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then bundle exec rake deploy; else bundle exec rake build; fi
